server:
  port: 6604

#注册中心信息
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.169.185:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  profiles:
    active: dev

---
spring:
  cloud:
    gateway:
      routes:
        - id: gateway-demo
          uri: lb://GATEWAY-DEMO
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
  profiles: dev

