eureka:
  instance:
    hostname: 47.107.169.185
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: true
    eureka-service-url-poll-interval-seconds: 30
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false